### ISSUE TITLE
Add an option to disable the frequency curve weigthing

### ISSUE THREAD

**Issue by ghost** [crlandsc/torch-log-wmse-audio-quality#1]
It would be great to have a option to easily disable the frequency curve weighting, when working on bass heavy audio (bass/drums/kick stems), it can lead to kinda unexpected results (high score while there are obvious audible issues in really low frequencies).

**Comment by crlandsc** [comment]
Good to know! You can bypass the frequency weighting currently by feeding in a custom IR that is just a Dirac (i.e. `[1, 0, 0, 0, ...]`). This will convolve the signal with a flat spectrum impulse instead of the frequency weighting.

However, this would use up unnecessary computation of course. So I will definitely add this feature! But you could use that as a janky workaround in the meantime.

Thanks for bringing this up, and I'd love it if you could share some of your "unexpected results" so I could document some "known issues" with this metric.

**Comment by crlandsc** [comment]
@jarredou This has been implemented in the latest release ([v0.2.9](https://github.com/crlandsc/torch-log-wmse/releases/tag/v0.2.9)). Just set `bypass_filter=True` in the `LogWMSE` instantiation and it will bypass the frequency weighting.

Let me know if this helps with the issues you were encountering!

**Comment by ghost** [comment]
I'm now on holidays, will try when back home ! Thanks a lot !
